# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUntitled():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_untitled(self):
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://www.51job.com/")
    # 2 | setWindowSize | 945x1020 | 
    self.driver.set_window_size(1920, 1080)
    # 3 | click | id=kwdselectid | 
    self.driver.find_element(By.ID, "kwdselectid").click()
    # 4 | type | id=kwdselectid | python
    self.driver.find_element(By.ID, "kwdselectid").send_keys("python")
    # 5 | click | id=work_position_input | 
    self.driver.find_element(By.ID, "work_position_input").click()
    # 6 | click | id=work_position_click_center_right_list_category_000000_080200 | 
    self.driver.find_element(By.ID, "work_position_click_center_right_list_category_000000_080200").click()
    # 7 | click | id=work_position_click_bottom_save | 
    self.driver.find_element(By.ID, "work_position_click_bottom_save").click()
    # 8 | click | css=button:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(2)").click()
    # 9 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 10 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
  
