# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test01():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_01(self):
    self.driver.get("https://blog.csdn.net/xia_yanbing/article/details/116300973")
    self.driver.set_window_size(945, 1020)
    element = self.driver.find_element(By.LINK_TEXT, "InsCode")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    self.driver.find_element(By.ID, "toolbar-search-input").click()
    self.driver.find_element(By.ID, "toolbar-search-input").send_keys("搜索")
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.ID, "toolbar-search-input").send_keys(Keys.ENTER)
    self.vars["win3430"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win3430"])
    self.driver.find_element(By.ID, "keyword").click()
    self.driver.find_element(By.CSS_SELECTOR, ".keyDown > .search-text").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "HTML+CSS实现搜索框").click()
    self.vars["win2044"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win2044"])
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(12)").click()
  
